name: Deployment

on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in AZURE

  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in AZURE
        env:
            PRIVATE_KEY: ${{ secrets.AZURE_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of AZURE and we will start the deploy .
            cd /home/ubuntu/CounterApp &&
            sudo git checkout main &&
            sudo git fetch --all &&
            sudo git reset --hard origin/main &&
            sudo git pull origin main
          '